/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package contraptions;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ContraptionsTest {
    /*
    @Test void appHasAGreeting() {
        Contraptions classUnderTest = new Contraptions();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    */
}
